### ISSUE TITLE
Investigate using caching in Github Actions instead of a docker image. 

### ISSUE THREAD

**Issue by philip-cc** [cyber-crypt-com/encryptonize-core#267]
**Description**
In order to avoid reinstalling all our dependencies on each Github Actions run we currently have a dedicated  [docker image](https://github.com/cyber-crypt-com/encryptonize-core/blob/master/.github/runner-image.dockerfile) with all dependencies. However, this means that our pipeline runs in a docker-next-to-docker setup, which often can have some annoying and hard to debug consequences.

An alternative approach would be to use Github Actions' [caching mechanism](https://docs.github.com/en/actions/advanced-guides/caching-dependencies-to-speed-up-workflows) so that we only install dependencies when they update. An action that implements this approach can be found [here](https://github.com/marketplace/actions/cache-anything-new).

Some thoughts:
* How does this behave with `apt` packages?
* Can this work with tools not managed by e.g. `apt`?
* Could we also cache go dependencies to reduce build times?

**Enabler for**
Fewer headaches in our pipelines.

**Comment by nela-cc** [comment]
**Findings**

* [**Setup Go environment**](https://github.com/marketplace/actions/setup-go-environment) action automatically installs and caches go.
* [**Cache**](https://github.com/marketplace/actions/cache) action allows [caching go modules](https://github.com/actions/cache/blob/main/examples.md#go---modules).
* [**Cache**](https://github.com/marketplace/actions/cache) action allows caching any downloaded dependencies as long as the installation path is specified. However, it is not that easy with apt packages since apt can store dependencies in different directories. Check out this [answer](https://stackoverflow.com/a/59277514). 
* [Github Actions virtual environments](https://github.com/actions/virtual-environments) already have many preinstalled tools. Check them out [here](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-Readme.md) for Ubuntu 20.04.
* There is no way to manually delete cache key. If the dependencies need to be updated the cache key must be modified from the code level. Alternatively, it's possible to use a secret as a version and modify it once the update must be performed, but it's just a workaround.
* Setup actions can't be running in parallel, because composite actions don't support jobs, only steps.
